# Change these first
owner: frpalmap # Your GitHub organization or username, where this repository lives
repo: uptimesipeca # The name of this repository

sites:
  - name: Ferretería
    url: www.ferreteriaportuguesa.com
  - name: Youtube
    url: www.youtube.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Fundacion Higea
    url: www.fundacionhigea.org
  - name: RedHigea
    url: www.redhigea.com
  - name: CDHM
    url: www.centrodiagnosticohigea.com
  - name: Itecnologica
    url: www.itecnologica.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptimesipeca
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Monitoring webpage configured by Fidel Palma, github pages hosted and powered by upptime.js [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
